apps/noticias/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'noticias'

urlpatterns = [
    path('', views.ListarNoticias, name='listar'),
    path('listarNoticia/', views.mostrarNoticia.as_view()), #clase
    path('detalle/<int:pk>', views.DetalleNoticias, name='detalle'),
    path('addNoticia', views.AddNoticia, name='addnoticia'),
    path('noticias/<int:pk>/edit/', views.EditNoticia, name='edit_noticia'),
    #url comentarios
    path('comment/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),
    path('comment/add/<int:noticia_id>/', views.add_comment, name='add_comment'),
    path('comment/edit/<int:comment_id>/', views.edit_comment, name='edit_comment'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    #1 parametro: es el texto de la url
    #2 parametro: la vista que se va a ejecutar
    #3 parametro: nombre de la url
    path("", views.Home, name="home"),
    path("nosotros/", views.Nosotros, name="nosotros"),
    path("contacto/", views.Contacto, name="contacto"),

    #urls aplicaciones
    path('noticias/', include('apps.noticias.urls')),
    path('usuarios/', include('apps.usuarios.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Yatchflix</title>
        <!-- Favicon-->
        <link rel="icon" type="image/ico" href="{% static 'claqueta.ico' %}">

        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>

    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container px-5">
                <a class="navbar-brand" href="#!">Cinema in your home.</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
             {% if user.is_authenticated %}
                <strong style="color: white;">Welcome  {{ user.username }}!</strong>
                <li class="nav-item"><a class="nav-link active" aria-current="page"  href="{% url 'logout' %}">LOGOUT</a> </li>
                {% else %}
                <li class="nav-item"><a class="nav-link active" aria-current="page"  href="{% url 'login' %}">LOGIN</a> </li>
                <li class="nav-item"><a class="nav-link active" aria-current="page"  href="{% url 'registro' %}">REGISTRO</a> </li>
                    <a href="{% url 'login' %}"></a>
                    <a href="{% url 'registro' %}"></a>
                {% endif %}

                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'nosotros' %}">About us</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'contacto' %}">Contact</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'noticias:listar' %}">News</a></li>
                    </ul>
                </div>
            </div>

            <style>
                /* Definir estilos para el navbar */
                nav {
                background-image: url"{% static 'assets/listapeliculas.jpg' %}"; /* Reemplaza 'ruta-de-tu-imagen.jpg' con la ruta de tu imagen de fondo */
                background-size: cover; /* Ajustar el tamaño de la imagen para cubrir el área del navbar */
                height: 80px; /* Establecer la altura deseada para tu navbar */
                /* Agrega otros estilos según tus necesidades */
                }


                /* Estilos para los enlaces dentro del navbar (opcional) */
                nav a {
                color: white; /* Cambiar el color del texto de los enlaces */
                /* Agrega otros estilos para los enlaces según tus necesidades */
                }
                </style>

        </nav>
        {% block contenido %}
        {% endblock contenido %}
        <!-- Footer-->
        <footer class="py-5 bg-dark">
            <div class="container px-5"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="{% static 'https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js' %}"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="{% static 'https://cdn.startbootstrap.com/sb-forms-latest.js'  %}"></script>
    </body>
</html>

templates/contacto.html
<!-- Bootstrap 5 Contact Form Snippet -->
{% extends 'base.html' %}



{% block titulo %}Contacto{% endblock titulo %}

{% block contenido %}
    
<div class="container px-5 my-5">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card border-0 rounded-3 shadow-lg">
          <div class="card-body p-4">
            <div class="text-center">
              <div class="h1 fw-light">Contact us</div>
              <p class="mb-4 text-muted">Send us a text to know your oponion!</p>
            </div>
  
            <!-- * * * * * * * * * * * * * *
            // * * SB Forms Contact Form * *
            // * * * * * * * * * * * * * * *
  
            // This form is pre-integrated with SB Forms.
            // To make this form functional, sign up at
            // https://startbootstrap.com/solution/contact-forms
            // to get an API token!
            -->
  
            <form id="contactForm" data-sb-form-api-token="API_TOKEN">
  
              <!-- Name Input -->
              <div class="form-floating mb-3">
                <input class="form-control" id="name" type="text" placeholder="Name" data-sb-validations="required" />
                <label for="name">Name</label>
                <div class="invalid-feedback" data-sb-feedback="name:required">Name is required.</div>
              </div>
  
              <!-- Email Input -->
              <div class="form-floating mb-3">
                <input class="form-control" id="emailAddress" type="email" placeholder="Email Address" data-sb-validations="required,email" />
                <label for="emailAddress">Email Address</label>
                <div class="invalid-feedback" data-sb-feedback="emailAddress:required">Email Address is required.</div>
                <div class="invalid-feedback" data-sb-feedback="emailAddress:email">Email Address Email is not valid.</div>
              </div>
  
              <!-- Message Input -->
              <div class="form-floating mb-3">
                <textarea class="form-control" id="message" type="text" placeholder="Message" style="height: 10rem;" data-sb-validations="required"></textarea>
                <label for="message">Message</label>
                <div class="invalid-feedback" data-sb-feedback="message:required">Message is required.</div>
              </div>
  
              <!-- Submit success message -->
              <div class="d-none" id="submitSuccessMessage">
                <div class="text-center mb-3">
                  <div class="fw-bolder">Message successful!</div>
                  <p>thanks for his message</p>
                  <a href="https://startbootstrap.com/solution/contact-forms"></a>
                </div>
              </div>
  
              <!-- Submit error message -->
              <div class="d-none" id="submitErrorMessage">
                <div class="text-center text-danger mb-3">Error sending message!</div>
              </div>
  
              <!-- Submit button -->
              <div class="d-grid">
                <button class="btn btn-primary btn-lg disabled" id="submitButton" type="submit">Submit</button>
              </div>
            </form>
            <!-- End of contact form -->
  
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <!-- CDN Link to SB Forms Scripts -->
  <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
  {% endblock contenido %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{%block contenido %}
    <!-- <head> <link rel="stylesheet" type="text/css" href="{% static 'miapp/css/miarchivo.css' %}"></head> -->
        <!-- Header-->
        
        <header class="bg-dark py-5 video-header">
            <video autoplay loop muted playsinline class="fullscreen-video">
                
                <source src="{% static 'network.mp4' %}" type="video/mp4">
                <!-- Agrega otros formatos de video aquí para mejorar la compatibilidad -->
            </video>
            
        
            <div class="container px-5">
                <!-- Contenido sobre el video -->
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <div class="text-center my-5">
                            <h1 class="display-5 fw-bolder text-white mb-2">Yatchflix</h1>
                            <p class="lead text-white-50 mb-4">Welcome user, find the best movies, documentaries and series. We provide you with the most effective and easy way to watch whatever you want whenever you want at any time.</p>
                            <div class="d-grid gap-3 d-sm-flex justify-content-sm-center">
                                <a class="btn btn-primary btn-lg px-4 me-sm-3" href="{% url 'login' %}">Login</a>
                                <a class="btn btn-outline-light btn-lg px-4" href="{% url 'registro' %}">Register</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Features section-->
        <section class="py-5 border-bottom" id="features">
            <div class="container px-5 my-5">
                <div class="row gx-5">
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"> <img width="200" height="250" src="{% static 'assets/ghost.jpg' %}" alt=""></div>
                        <h2 class="h4 fw-bolder">Ghostbusters</h2>
                        <p>Four unemployed paranormal investigators create a company in New York with the purpose of cleaning the city of ghosts.</p>
                        <a class="text-decoration-none" href="https://www.youtube.com/watch?v=6hDkhw5Wkas&ab_channel=RottenTomatoesClassicTrailers">
                            Watch the trailer 
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><img width="200" height="250" src="{% static 'assets/future.jpg' %}" alt=""></div>
                        <h2 class="h4 fw-bolder">Back to the future 2</h2>
                        <p>A teenager and a quirky inventor travel back in time and into the future to alter a series of disastrous events.</p>
                        <a class="text-decoration-none" href="https://www.youtube.com/watch?v=MdENmefJRpw&ab_channel=RottenTomatoesClassicTrailers">
                            Watch the trailer 
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                    <div class="col-lg-4">
                        <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><img width="200" height="250" src="{% static 'assets/beet.jpg' %}" alt="">></div>
                        <h2 class="h4 fw-bolder">Beetlejuice</h2>
                        <p>A couple who have just died hire a vulgar ghost to scare the new occupants of their house.</p>
                        <a class="text-decoration-none" href="https://www.youtube.com/watch?v=ickbVzajrk0&ab_channel=RottenTomatoesClassicTrailers">
                            Watch the trailer 
                            <i class="bi bi-arrow-right"></i>
                        </a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Pricing section-->
        
        <!-- Testimonials section-->
        <section class="py-5 border-bottom">
            <div class="container px-5 my-5 px-5">
                <div class="text-center mb-5">
                    <h2 class="fw-bolder">Testimonials.</h2>
                    <p class="lead mb-0">Our members love us.</p>
                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-6">
                        <!-- Testimonial 1-->
                        <div class="card mb-4">
                            <div class="card-body p-4">
                                <div class="d-flex">
                                    <div class="flex-shrink-0"><i class="bi bi-chat-right-quote-fill text-primary fs-1"></i></div>
                                    <div class="ms-4">
                                        <p class="mb-1">Best digital web application to see what you want, I have never seen anything like this before. Very fast and effective!</p>
                                        <div class="small text-muted">- Marcus Thorne, Wellington-New Zealand</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Testimonial 2-->
                        <div class="card">
                            <div class="card-body p-4">
                                <div class="d-flex">
                                    <div class="flex-shrink-0"><i class="bi bi-chat-right-quote-fill text-primary fs-1"></i></div>
                                    <div class="ms-4">
                                        <p class="mb-1">Amazing! I have no words to describe how wonderful this application is. Highly recommended!</p>
                                        <div class="small text-muted">- Ava Winters, London-England</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- Contact section-->
{% endblock contenido %}
        

templates/nosotros.html
{% extends 'base.html' %}
{% load static %}


{% block titulo %}NOSOTROS{% endblock titulo %}

{% block contenido %}
<header>
    <link rel="stylesheet" href="{% static 'css/video.css' %}">
    <!-- This div is  intentionally blank. It creates the transparent black overlay over the video which you can modify in the CSS -->
    <div class="overlay"></div>

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NOSOTROS</title>
</head>

<body>

  <iframe width="3000" height="2000" src="https://www.youtube.com/embed/JQerdtHqTXQ?modestbranding=0&controls=0&mute=1&autoplay=1"
      title="YouTube video player" frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
      allowfullscreen></iframe>
</body>
    <!-- The HTML5 video element that will create the background video on the header -->
    <!--<video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
      <source src="https://source.unsplash.com/XT5OInaElMw/1600x900" type="image.png">
    </video>-->

    <!-- The header content -->
    <div class="container h-100">
      <div class="d-flex h-100 text-center align-items-center">
        <div class="w-100 text-white">
          <h1 class="display-3"></h1>
          <p class="lead mb-0"></p>
        </div>
      </div>
    </div>
  </header>

  <!-- Page section example for content below the video header -->
  <section class="my-5">
    <div class="container">
      <div class="row">
        <div class="col-md-8 mx-auto">

          <h1>About us</h1>
          <h5>Who are we?</h5>
          <p>We are a digital platform that tries to offer the best service and try to reach as many people as possible.</p>
          <h5>Our content:</h5>
          <p>Our content is based on retro type movies whether comedy, science fiction, drama, trhiller, horror and many other genres.</p>
          <h5>Our community:</h5>
          <p>In our community we try to make all movie lovers feel identified with at least one of the movies that we have to offer. We also want to provide support and the best service to make you feel comfortable at all times.</p>
          <p class="mb-0">
            For more information let us know your opinion.<a href="{% url 'contacto' %}"></a>
            <div>            <br>                  </div>
            <h4>• Members •</h4>
            <h6>Federico Durnbeck</h6>
            <h6>Lucas David Barboza</h6>
            <h6>Lucas Ezequiel Giroldi</h6>
            <h6>Pedro Sanso Wilfredo</h6>
            <h6>Lautaro Landriel Alfredo</h6>
            <h6>Juan Gilberto Nuñez Barua</h6>
            <h6>Lucas Bautista Abson</h6>
          </p>
        </div>
      </div>
    </div>
  </section>
{% endblock contenido %}